In [75]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Standardization request for input survey

- Year(s) of Major Renovation(s): comma-separated numerics only. 
- Seismic Upgrade Year: Should restrict to significant upgrades to the lateral force-resisting systems. comma-separated numerics only. 
- Floors Below Grade: is grade-fixity good enough for fixed? Should we model basement as floor 1?
- Primary dimension of the building (length) in main directions
- Higher priority on story heights
- Length of just LFRS (m)

### Handle Excel

A better output would be to ask the user to manually use Excel to export the first sheet to CSV.

In [76]:
'''
import os 
import pandas as pd
from pathlib import Path

file_path = os.getcwd()
proj_root = os.path.dirname(file_path)

refm_excel_path = Path(file_path) / 'refm.xlsx'
output_csv = 'refm.csv'

# convert first sheet of the excel
df = pd.read_excel(refm_excel_path, sheet_name=0)

df.to_csv(output_csv, index=False)
'''

"\nimport os \nimport pandas as pd\nfrom pathlib import Path\n\nfile_path = os.getcwd()\nproj_root = os.path.dirname(file_path)\n\nrefm_excel_path = Path(file_path) / 'refm.xlsx'\noutput_csv = 'refm.csv'\n\n# convert first sheet of the excel\ndf = pd.read_excel(refm_excel_path, sheet_name=0)\n\ndf.to_csv(output_csv, index=False)\n"

In [77]:
import mimlos.mimlos.inventory as inv
import mimlos
import os 
import pandas as pd
from pathlib import Path

In [78]:
file_path = os.getcwd()
raw_csv = Path(file_path) / 'refm.csv'
inventory = inv.Inventory.load_from_csv(raw_csv)

In [79]:
df_raw = inventory.df_raw
print(df_raw['Seismic Force Resisting System in the East-West Direction'].unique())
print(df_raw['Seismic Force Resisting System in the North-South Direction'].unique())
print(df_raw['Site Class'].unique())

['CIW' nan 'CSW' 'RMC' 'WLF' 'WLF-P9' 'URM' 'SBF' 'PCW']
['CIW' nan 'CSW' 'RMC' 'WLF' 'WLF-P9' 'URM' 'PCW' 'WPB']
['C' nan 'E' 'D']

In [80]:
inventory.inventory_df

,ID,Facility/Asset,Address,Review Phase,Approver,Screener,Drawings,Desktop Review Date,Site Visit,Site Review Date,...,FEMA P154 RVS Level 2 Screening S-Score,SEG Level 2 - SQST S-Score,Building: Collapse Likelihood,Building: Post Disaster Importance,Building: Occupancy,Building: Seismic Screening Data,Building: Seismic S Score,Building: Seismic Risk,Longitude,Latitude
0,12,CULT_1064_601 Smithe St_Orpheum Theatre,601 Smithe St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,19-Sep-25,Adequate,19-Sep-25,...,0.3,0.3,8%,High Occupancy-A,1000+,NaN,1.1000000000000001,High,-123.120526,49.280063
172,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,1.2,1.5,1.3% and 0.016%,Emergency Shelter,101-1000,NaN,1.9,Medium,-123.074743,49.237271
173,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,1.0,2,1.3% and 0.016%,Emergency Shelter,101-1000,NaN,1.9,Medium,-123.074743,49.237271
174,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,2.0,1.8,1.3% and 0.016%,Emergency Shelter,101-1000,NaN,1.9,Medium,-123.074743,49.237271
175,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,1.5,1.9,1.3% and 0.016%,Emergency Shelter,101-1000,NaN,1.9,Medium,-123.074743,49.237271
199,273,NONM_7904_1261 Granville St_Granville Residence,1261 Granville St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,0.2,0.3,15%,High Occupancy,11-100,NaN,-0.5,High,-123.127323,49.276628
204,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,4.1,4.6,0.2%,Reception Centre,101-1000,NaN,2.7,Low,-123.043079,49.227204
205,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,1.1,1.3,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
206,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,NaN,24-Sep-25,Adequate,24-Sep-25,...,4.0,3.9,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
207,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,1.3,2.3,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
222,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Partial (Exterior),24-Sep-25,...,1.7,1.8,15%,Reception Centre,101-1000,NaN,-0.3,High,-123.039428,49.280804
223,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,0.5,0.4,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
224,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,1.0,1.1,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
225,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,0.7,0.4,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
231,294,CULT_1418_3102 Main St_Heritage Hall_MIXU,3102 Main St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,0.6,0.3,15%,Emergency Shelter,101-1000,NaN,0.2,High,-123.100839,49.257296

In [81]:
inventory.inventory_df.columns

Index(['ID', 'Facility/Asset', 'Address', 'Review Phase', 'Approver',
       'Screener', 'Drawings', 'Desktop Review Date', 'Site Visit',
       'Site Review Date', 'Ready for Approval?', 'Approved?', 'Building Name',
       'Development Category Indicator', 'Custom: CoV Ownership Status',
       'SAP Building Number', 'Date Built', 'Year Built',
       'NBC Code Year (Original Building)',
       'Current Replacement Value (June 2026)',
       'Gross Size (sq.ft.) - from Asset Planner - June 2026', 'CRV/sq.ft.',
       'Floors Above Grade', 'Floors Below Grade', 'Building: General Summary',
       'Building: Architectural Summary', 'Building: Heritage',
       'Year(s) of Major Renovation(s)', 'Description of Major Renovation',
       'Building: Main Superstructure Material',
       'Vertical Load Bearing System', 'Roof System', 'Floor System',
       'Seismic Force Resisting System in the North-South Direction',
       'Seismic Force Resisting System in the East-West Direction',
       'Number of LDRS Bays in North-South Direction',
       'Number of LDRS Bays in East-West Direction', 'Seismic Upgrade Year',
       'Description of Seismic Upgrade', 'Seismic Upgrading Case',
       'Building Height (Total Height Above Ground (m) to Roof Slab)',
       '"Original" Building Importance Factor Ie',
       'Building Importance Factor Ie - Based on VBBL 2025 - Upgraded',
       'Occupancy Type', 'Service Group', 'Replacement Cost (June 2026 $$)',
       'At-risk Population: Y/N?', 'Site Class', 'Basement',
       'Basement Floor Plan Area (sq.m.)', 'Ground Floor Plan Area (sq.m.)',
       'Roof Plan Area (sq.m.)', 'Geological Hazards',
       'Significant Alterations or Deviations', 'Material Conditions',
       'Sesimic Isolation / Energy Dissipation Systems',
       'Separation / Distance from Adjacent Structures (mm)',
       'Pounding Type Input', 'Pounding Type', 'Vertical Irregularity Input',
       'Vertical Irregularity Description', 'Plan Irregularity Input',
       'Plan Irregularity Description', 'Building Irregularity',
       'Falling Hazards (Y/N)',
       'Exterior Non-structural Components - Restrained (Y/N)',
       'Interior Non-structural Components - Restrained (Y/N)', 'URM (Y/N)',
       'FEMA P154 Special Cases', 'Remaining Occupancy Time',
       'Category Functionality Class',
       'Gross Area (including basement) (sq.m.)', 'Seismic Weight (kN)',
       'Snow Load and Roof Weight (kN)', 'Floor Weight - Above Grade (kN)',
       'LDRS Weight North-South Direction (kN)',
       'LDRS Weight East-West Direction (kN)',
       'Content Weight Based on Occupancy Type (kN)',
       'FEMA P154 RVS Level 2 Screening S-Score', 'SEG Level 2 - SQST S-Score',
       'Building: Collapse Likelihood', 'Building: Post Disaster Importance',
       'Building: Occupancy', 'Building: Seismic Screening Data',
       'Building: Seismic S Score', 'Building: Seismic Risk', 'Longitude',
       'Latitude'],
      dtype='object')

TODO: solve environment to install openseespy

## Property estimations

### Building strength

1) Identify latest year of code-renovations or construction
2) Match to NBCC code year

In [82]:
# inventory.preprocess_inventory()
inventory.estimate_Vs()
inventory.determine_hazus_parameters()
inventory.estimate_loads()
inventory.estimate_capacities()

In [83]:
my_inv = inventory.inventory_df
my_inv

,ID,Facility/Asset,Address,Review Phase,Approver,Screener,Drawings,Desktop Review Date,Site Visit,Site Review Date,...,FEMA_lfrs_ew,hazus_Cs_design_strength,hazus_Omega_y_yield_overstrength,hazus_Omega_p_peak_overstrength,hazus_mu_ductility,weight_x_N,vertical_load_x_Pa,Vdj_story_design_shear,Vyj_story_yield_shear,Vpj_story_peak_shear
0,12,CULT_1064_601 Smithe St_Orpheum Theatre,601 Smithe St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,19-Sep-25,Adequate,19-Sep-25,...,C3M,"(0.05, 0.05)","(1.25, 1.25)","(2.25, 2.25)","(3.3, 3.3)","[8700.0, 8700.0, 8700.0, 8700.0, 8200.0]","[8.7, 8.7, 8.7, 8.7, 8.2]","([0.020000000000000004, 0.01854545454545455, 0...","([0.025000000000000005, 0.023181818181818185, ...","([0.05625000000000001, 0.05215909090909092, 0...."
172,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,C2L,"(0.05, 0.05)","(1.5, 1.5)","(2.5, 2.5)","(5.0, 5.0)",[8460.0],[7.05],"([0.108], [0.108])","([0.162], [0.162])","([0.405], [0.405])"
173,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,RM2L,"(0.133, 0.133)","(1.5, 1.5)","(2.0, 2.0)","(6.0, 6.0)","[5101.2, 2550.6]","[11.7, 5.85]","([0.27, 0.162], [0.27, 0.162])","([0.405, 0.243], [0.405, 0.243])","([0.81, 0.486], [0.81, 0.486])"
174,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,C2L,"(0.05, 0.05)","(1.5, 1.5)","(2.5, 2.5)","(5.0, 5.0)",[1311.3],[7.05],"([0.09217101712624418], [0.09217101712624418])","([0.13825652568936625], [0.13825652568936625])","([0.3456413142234156], [0.3456413142234156])"
175,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,RM2L,"(0.067, 0.067)","(1.5, 1.5)","(2.0, 2.0)","(5.0, 5.0)",[3690.0],[6.0],"([0.10920000000000002], [0.10920000000000002])","([0.16380000000000003], [0.16380000000000003])","([0.32760000000000006], [0.32760000000000006])"
199,273,NONM_7904_1261 Granville St_Granville Residence,1261 Granville St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,URMM,"(0.067, 0.067)","(1.25, 1.25)","(2.0, 2.0)","(3.3, 3.3)","[4350.0, 4350.0, 4350.0, 4350.0, 4100.0]","[8.7, 8.7, 8.7, 8.7, 8.2]","([0.020000000000000004, 0.01854545454545455, 0...","([0.025000000000000005, 0.023181818181818185, ...","([0.05000000000000001, 0.04636363636363637, 0...."
204,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,C2L,"(0.1, 0.1)","(1.5, 1.5)","(2.5, 2.5)","(6.0, 6.0)",[707.0],[5.05],"([0.27582285714285704, 0.13791142857142852], [...","([0.41373428571428555, 0.20686714285714278], [...","([1.034335714285714, 0.517167857142857], [1.03..."
205,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,RM2L,"(0.133, 0.133)","(1.5, 1.5)","(2.0, 2.0)","(6.0, 6.0)","[5244.0, 4816.5]","[9.2, 8.45]","([0.18000000000000002, 0.10800000000000001], [...","([0.27, 0.16200000000000003], [0.27, 0.1620000...","([0.54, 0.32400000000000007], [0.54, 0.3240000..."
206,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,NaN,24-Sep-25,Adequate,24-Sep-25,...,S2L,"(0.1, 0.1)","(1.5, 1.5)","(2.5, 2.0)","(6.0, 6.0)",[12435.5],[5.95],"([0.27582285714285704, 0.13791142857142852], [...","([0.41373428571428555, 0.20686714285714278], [...","([1.034335714285714, 0.517167857142857], [1.18..."
207,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,PC1,"(0.1, 0.1)","(1.5, 1.5)","(2.0, 2.0)","(6.0, 6.0)",[11997.0],[6.45],"([0.5940799999999999, 0.29703999999999997], [0...","([0.8911199999999999, 0.44555999999999996], [0...","([1.7822399999999998, 0.8911199999999999], [1...."
222,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Partial (Exterior),24-Sep-25,...,W2,"(0.05, 0.05)","(1.5, 1.5)","(2.5, 2.5)","(6.0, 6.0)","[780.2, 655.7]","[4.7, 3.95]","([0.02, 0.012], [0.02, 0.012])","([0.03, 0.018000000000000002], [0.03, 0.018000...","([0.075, 0.045000000000000005], [0.075, 0.0450..."
223,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,C2L,"(0.05, 0.05)","(1.5, 1.5)","(2.5, 2.5)","(5.0, 5.0)",[2592.6],[7.45],"([0.1090909090909091], [0.1090909090909091])","([0.16363636363636364], [0.16363636363636364])","([0.40909090909090906], [0.40909090909090906])"
224,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,URML,"(0.067, 0.067)","(1.5, 1.5)","(2.0, 2.0)","(5.0, 5.0)","[2346.0, 2154.75]","[9.2, 8.45]","([0.15340909090909094, 0.09204545454545456], [...","([0.2301136363636364, 0.13806818181818184], [0...","([0.4602272727272728, 0.2761363636363637], [0...."
225,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,C2L,"(0.05, 0.05)","(1.5, 1.5)","(2.5, 2.5)","(5.0, 5.0)",[5215.0],[7.45],"([0.1090909090909091], [0.1090909090909091])","([0.16363636363636364], [0.16363636363636364])","([0.40909090909090906], [0.40909090909090906])"
231,294,CULT_1418_3102 Main St_Heritage Hall_MIXU,3102 Main St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,C3L,"(0.05, 0.05)","(1.5, 1.5)","(2.25, 2.25)","(5.0, 5.0)","[4611.0, 4611.0, 4346.0]","[8.7, 8.7, 8.2]","([0.020000000000000004, 0.016190476190476193, ...","([0.030000000000000006, 0.02428571428571429, 0...","([0.06750000000000002, 0.05464285714285715, 0...."

### Tester

In [84]:
import numpy as np
code_years = [1941, 1953, 1960, 1965, 1970, 1975, 1977, 1980, 1985, 1990, 1995, 2005, 2010, 2015, 2020, 2025]
n_stories = 2
test_df = pd.DataFrame({
    "NBC Code Year (Original Building)": code_years,
    "Seismic Upgrade Year": "",
    "Year Built": code_years,
    "Seismic Force Resisting System in the North-South Direction": "CMF",
    "Seismic Force Resisting System in the East-West Direction": "CSW",
    "Building Height (Total Height Above Ground (m) to Roof Slab)": 3.5*n_stories*np.ones(len(code_years)),
    "Floors Above Grade": n_stories * np.ones(len(code_years)),
    "Site Class": "C",
    "Ground Floor Plan Area (sq.m.)": (30.0**2) * np.ones(len(code_years)),
    '"Original" Building Importance Factor Ie': np.ones(len(code_years)),
    "Approved?" : 'Yes'
})
    
test_inventory = inv.Inventory.load_from_df(test_df)
test_inventory.estimate_Vs()

In [85]:
tst = test_inventory.inventory_df
tst

,NBC Code Year (Original Building),Seismic Upgrade Year,Year Built,Seismic Force Resisting System in the North-South Direction,Seismic Force Resisting System in the East-West Direction,Building Height (Total Height Above Ground (m) to Roof Slab),Floors Above Grade,Site Class,Ground Floor Plan Area (sq.m.),"""Original"" Building Importance Factor Ie",Approved?,latest_seismic_upgrade_year,original_nbcc_year,effective_nbcc_year,T_n,original_nbcc_unfactored_Vd,original_nbcc_factored_Ve,SEG_adjusted_NBCC_factored_Ve,NBCC_2025_unfactored_Vd,Vd_distributed_SEG_adjusted_NBCC_factored_Ve
0,1941,,1941,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1941,1941,"([0.32276378029941377, 0.08585516555964406], [...","(0.02, 0.02)","(0.04, 0.04)","(0.02, 0.02)","([1.0116100781844222, 1.1], [1.089073385456281...","([0.02, 0.012], [0.02, 0.012])"
1,1953,,1953,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1953,1953,"([0.32276378029941377, 0.08585516555964406], [...","(0.0923076923076923, 0.0923076923076923)","(0.1846153846153846, 0.1846153846153846)","(0.0923076923076923, 0.0923076923076923)","([1.0116100781844222, 1.1], [1.089073385456281...","([0.0923076923076923, 0.05538461538461538], [0..."
2,1960,,1960,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1960,1960,"([0.32276378029941377, 0.08585516555964406], [...","(0.0923076923076923, 0.0923076923076923)","(0.1846153846153846, 0.1846153846153846)","(0.0923076923076923, 0.0923076923076923)","([1.0116100781844222, 1.1], [1.089073385456281...","([0.0923076923076923, 0.05538461538461538], [0..."
3,1965,,1965,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1965,1965,"([0.32276378029941377, 0.08585516555964406], [...","(0.06818181818181818, 0.11363636363636365)","(0.09204545454545454, 0.15340909090909094)","(0.09204545454545454, 0.15340909090909094)","([1.0242552041617277, 1.1137500000000002], [1....","([0.09204545454545454, 0.05522727272727272], [..."
4,1970,,1970,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1970,1970,"([0.32276378029941377, 0.08585516555964406], [...","(0.067, 0.1)","(0.12060000000000001, 0.18000000000000002)","(0.09045000000000002, 0.135)","([0.18333333333333335, 0.18333333333333335], [...","([0.09045, 0.054270000000000006], [0.135, 0.081])"
5,1975,,1975,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1975,1975,"([0.32276378029941377, 0.08585516555964406], [...","(0.047879326506947505, 0.08)","(0.08618278771250551, 0.14400000000000002)","(0.06463709078437914, 0.10800000000000001)","([0.48888888888888893, 0.48888888888888893], [...","([0.06463709078437915, 0.03878225447062749], [..."
6,1977,,1977,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1977,1977,"([0.32276378029941377, 0.08585516555964406], [...","(0.047879326506947505, 0.08)","(0.08618278771250551, 0.14400000000000002)","(0.06463709078437914, 0.10800000000000001)","([0.48888888888888893, 0.48888888888888893], [...","([0.06463709078437915, 0.03878225447062749], [..."
7,1980,,1980,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1980,1980,"([0.32276378029941377, 0.08585516555964406], [...","(0.055999999999999994, 0.08)","(0.10079999999999999, 0.14400000000000002)","(0.0756, 0.10800000000000001)","([0.48888888888888893, 0.48888888888888893], [...","([0.0756, 0.045360000000000004], [0.1080000000..."
8,1985,,1985,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1985,1985,"([0.32276378029941377, 0.08585516555964406], [...","(0.0616, 0.08482554348350266)","(0.09240000000000001, 0.12723831522525397)","(0.08316000000000001, 0.1145144837027286)","([0.48888888888888893, 0.48888888888888893], [...","([0.08316000000000001, 0.049896], [0.114514483..."
9,1990,,1990,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1990,1990,"([0.32276378029941377, 0.08585516555964406], [...","(0.09000000000000001, 0.17314317392436573)","(0.09000000000000001, 0.17314317392436573)","(0.09000000000000001, 0.17314317392436573)","([0.18333333333333335, 0.18333333333333335], [...","([0.09000000000000001, 0.054000000000000006], ..."
10,1995,,1995,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,1995,1995,"([0.32276378029941377, 0.08585516555964406], [...","(0.0821415117276633, 0.17314317392436573)","(0.0821415117276633, 0.17314317392436573)","(0.0821415117276633, 0.17314317392436573)","([0.18333333333333335, 0.18333333333333335], [...","([0.0821415117276633, 0.04928490703659798], [0..."
11,2005,,2005,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,2005,2005,"([0.32276378029941377, 0.08585516555964406], [...","([0.09215686274509803, 0.09215686274509803], [...","([0.09215686274509803, 0.09215686274509803], [...","([0.09215686274509803, 0.09215686274509803], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.09215686274509803, 0.05529411764705882], [..."
12,2010,,2010,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,2010,2010,"([0.32276378029941377, 0.08585516555964406], [...","([0.09215686274509803, 0.09215686274509803], [...","([0.09215686274509803, 0.09215686274509803], [...","([0.09215686274509803, 0.09215686274509803], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.09215686274509803, 0.05529411764705882], [..."
13,2015,,2015,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,2015,2015,"([0.32276378029941377, 0.08585516555964406], [...","([0.08313725490196078, 0.08313725490196078], [...","([0.08313725490196078, 0.08313725490196078], [...","([0.08313725490196078, 0.08313725490196078], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.08313725490196078, 0.04988235294117646], [..."
14,2020,,2020,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,2020,2020,"([0.32276378029941377, 0.08585516555964406], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490195, 0.06470588235294117], [..."
15,2025,,2025,CMF,CSW,7.0,2.0,C,900.0,1.0,Yes,<NA>,2025,2025,"([0.32276378029941377, 0.08585516555964406], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490197, 0.10784313725490197], [...","([0.10784313725490195, 0.06470588235294117], [..."

In [86]:

DESIGN_HAZARD_PATH = Path(mimlos.__file__).resolve().parent / "mimlos" / "data" / "hazard" / "design"
VANCOUVER_CITY_HALL_DESIGN_HAZARD_2020 = pd.read_csv(
    DESIGN_HAZARD_PATH / '2020_BC_Vancouver_cityhall_Hoteldeville.csv',
    encoding="cp863")

VANCOUVER_CITY_HALL_DESIGN_HAZARD_2020.rename(
    columns={VANCOUVER_CITY_HALL_DESIGN_HAZARD_2020.columns[0]: "site_designation"}, inplace=True)
VANCOUVER_CITY_HALL_DESIGN_HAZARD_2020.set_index('site_designation', inplace=True)
VANCOUVER_CITY_HALL_DESIGN_HAZARD_2020

,2%/50 Sa(0.2),2%/50 Sa(0.5),2%/50 Sa(1.0),2%/50 Sa(2.0),2%/50 Sa(5.0),2%/50 Sa(10.0),2%/50 PGA,2%/50 PGV,Unnamed: 9,5%/50 Sa(0.2),...,5%/50 PGV,Unnamed: 18,10%/50 Sa(0.2),10%/50 Sa(0.5),10%/50 Sa(1.0),10%/50 Sa(2.0),10%/50 Sa(5.0),10%/50 Sa(10.0),10%/50 PGA,10%/50 PGV
site_designation,,,,,,,,,,,,,,,,,,,,,
XE,1.130,1.240,0.954,0.606,0.1880,0.0670,0.525,0.860,NaN,0.827,...,0.549,NaN,0.637,0.661,0.460,0.2390,0.0562,0.01820,0.290,0.376
XD,1.130,1.180,0.837,0.509,0.1530,0.0571,0.520,0.769,NaN,0.826,...,0.500,NaN,0.628,0.614,0.398,0.2010,0.0473,0.01590,0.282,0.344
XC,1.100,0.884,0.513,0.312,0.0882,0.0372,0.479,0.533,NaN,0.777,...,0.350,NaN,0.569,0.437,0.238,0.1220,0.0294,0.01090,0.247,0.242
XB,0.845,0.515,0.293,0.185,0.0505,0.0238,0.375,0.323,NaN,0.578,...,0.214,NaN,0.416,0.251,0.135,0.0728,0.0180,0.00737,0.187,0.147
XA,0.687,0.401,0.228,0.149,0.0454,0.0226,0.323,0.260,NaN,0.467,...,0.171,NaN,0.334,0.193,0.104,0.0587,0.0157,0.00671,0.159,0.117

### NMFS properties

Roadmap:
1) Estimate building weight $W$ from floor area
2) use for density $\rho$
3) Calculate $GA$ and $EI$ from Xiong equations. Later adjustments to stiffness would happen here.
4) Get $\Delta_y$, $\Omega_y$, $\Omega_p$ from HAZUS classification
5) Calculate $V_y$ from $V_d W$ and $\Omega_y$
5) Calculate $V_p$ from $V_y W$ and $\Omega_p$
6) Calculate $\Delta_y$ and $\Delta_p$ from Xiong equation 19
7) Estimate $\Delta_c$ corresponding to collapse


Moment world: 
1) Need bending moment design strength from code

In [87]:
import numpy as np
import pandas as pd
from openquake.vmtk.units import units
from scipy.optimize import least_squares
from math import sin, sinh, cos, cosh

def calculate_parameters(T_n, H):
    T_1 = T_n[0]
    T_2 = T_n[-1]

    omega_n = 2*units.pi/T_n

def flexural_shear_eigen(parameters, T_1, T_2):
    gamma_1 = parameters[0]
    gamma_2 = parameters[1]
    alpha_0 = parameters[-1]

    period_ratio_eqn = gamma_1/gamma_2 * ((gamma_1**2 + alpha_0**2)/
                                          (gamma_2**2 + alpha_0**2))**0.5 - (T_2 / T_1)
    char_eq_1 = (2 + 
                 (2 + alpha_0**4 / (gamma_1**2*(gamma_1**2 + alpha_0**2)))*
                 cos(gamma_1) * cosh((alpha_0**2 + gamma_1**2)**0.5) +
                 alpha_0**2 / (gamma_1*(gamma_1**2 + alpha_0**2)**0.5)*
                 sin(gamma_1) * sinh((alpha_0**2 + gamma_1**2)**0.5))
    
    char_eq_2 = (2 + 
                 (2 + alpha_0**4 / (gamma_2**2*(gamma_2**2 + alpha_0**2)))*
                 cos(gamma_2) * cosh((alpha_0**2 + gamma_2**2)**0.5) +
                 alpha_0**2 / (gamma_2*(gamma_2**2 + alpha_0**2)**0.5)*
                 sin(gamma_2) * sinh((alpha_0**2 + gamma_2**2)**0.5))

    return [period_ratio_eqn, char_eq_1, char_eq_2]

initial_guess = [1.875, 4.694, 2.0]
T_1 = 0.3
T_2 = 0.3 * 0.27
solution = least_squares(
    flexural_shear_eigen,
    initial_guess,
    args=(T_1, T_2),
    bounds=([1e-6, 1e-6, 0.0],
            [np.inf, np.inf, np.inf])
)

gamma_1, gamma_2, alpha_0 = solution.x
print(solution)

     message: `gtol` termination condition is satisfied.
     success: True
      status: 1
         fun: [-2.220e-16  5.684e-14  2.842e-13]
           x: [ 1.905e+00  4.933e+00  4.024e+00]
        cost: 4.2005290133111725e-26
         jac: [[ 1.677e-01 -8.760e-02  2.801e-02]
               [-2.410e+02  0.000e+00 -9.165e+00]
               [ 0.000e+00  7.110e+02 -4.601e+01]]
        grad: [-1.370e-11  2.021e-10 -1.360e-11]
  optimality: 9.969463424899048e-10
 active_mask: [0 0 0]
        nfev: 68
        njev: 65