In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Handle Excel

A better output would be to ask the user to manually use Excel to export the first sheet to CSV.

In [8]:
'''
import os 
import pandas as pd
from pathlib import Path

file_path = os.getcwd()
proj_root = os.path.dirname(file_path)

refm_excel_path = Path(file_path) / 'refm.xlsx'
output_csv = 'refm.csv'

# convert first sheet of the excel
df = pd.read_excel(refm_excel_path, sheet_name=0)

df.to_csv(output_csv, index=False)
'''

"\nimport os \nimport pandas as pd\nfrom pathlib import Path\n\nfile_path = os.getcwd()\nproj_root = os.path.dirname(file_path)\n\nrefm_excel_path = Path(file_path) / 'refm.xlsx'\noutput_csv = 'refm.csv'\n\n# convert first sheet of the excel\ndf = pd.read_excel(refm_excel_path, sheet_name=0)\n\ndf.to_csv(output_csv, index=False)\n"

In [9]:
from mimlos.mimlos.inventory import Inventory

import os 
import pandas as pd
from pathlib import Path

file_path = os.getcwd()
raw_csv = Path(file_path) / 'refm.csv'
inventory = Inventory.load_from_csv(raw_csv)

In [10]:
inventory.df_raw

,ID,Facility/Asset,Address,Review Phase,Approver,Screener,Drawings,Desktop Review Date,Site Visit,Site Review Date,...,FEMA P154 RVS Level 2 Screening S-Score,SEG Level 2 - SQST S-Score,Building: Collapse Likelihood,Building: Post Disaster Importance,Building: Occupancy,Building: Seismic Screening Data,Building: Seismic S Score,Building: Seismic Risk,Longitude,Latitude
0,12,CULT_1064_601 Smithe St_Orpheum Theatre,601 Smithe St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,19-Sep-25,Adequate,19-Sep-25,...,0.3,0.3,8%,High Occupancy-A,1000+,NaN,1.1000000000000001,High,-123.120526,49.280063
1,13,CULT_8809_843 Seymour St_VSO Music School / Re...,843 Seymour St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,NaN,High Occupancy,Unknown,NaN,10,Pre-Screen Low,-123.119708,49.280335
2,14,CULT_8809_823 Seymour St_Orpheum Rehearsal Hal...,823 Seymour St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,NaN,NaN,Unknown,NaN,10,Pre-Screen Low,-123.119434,49.280551
3,15,CULT_1001_578 Carrall St_Sun Yat-Sen Classical...,578 Carrall St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,2%,NaN,11-100,NaN,1.7,Medium,-123.104117,49.279800
4,17,ENEX_7315_2901 E Hastings St_PNE - Livestock B...,2901 E Hastings St,Phase 1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,0.3%,High Occupancy-A,1000+,NaN,2.6,Low,-123.039784,49.284227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,4088,COMM_11194_1606 W 5th Av,1606 W 5th Av,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.141230,49.266877
715,4095,RECR_11097_7780 Oak St_Marpole Oakridge Commun...,7780 Oak St,NOT IN SCOPE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.129027,49.214782
716,4096,CWYD_1347_290 E 51st Av_Sunset Nursery - Admin...,290 E 51st Av,NOT IN SCOPE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.098868,49.223297
717,4150,DAYC_7002_3010 E Kent Av South_Salmon Stone Da...,3010 E Kent Av South,Phase 1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.044632,49.206140
718,4151,PARK_7002_3010 E Kent Av South_Park Washroom (...,3010 E Kent Av South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.044632,49.206140

In [11]:
inventory.df_clean

,ID,Facility/Asset,Address,Review Phase,Approver,Screener,Drawings,Desktop Review Date,Site Visit,Site Review Date,...,FEMA P154 RVS Level 2 Screening S-Score,SEG Level 2 - SQST S-Score,Building: Collapse Likelihood,Building: Post Disaster Importance,Building: Occupancy,Building: Seismic Screening Data,Building: Seismic S Score,Building: Seismic Risk,Longitude,Latitude
0,12,CULT_1064_601 Smithe St_Orpheum Theatre,601 Smithe St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,19-Sep-25,Adequate,19-Sep-25,...,0.3,0.3,8%,High Occupancy-A,1000+,NaN,1.1000000000000001,High,-123.120526,49.280063
173,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,1.0,2,1.3% and 0.016%,Emergency Shelter,101-1000,NaN,1.9,Medium,-123.074743,49.237271
199,273,NONM_7904_1261 Granville St_Granville Residence,1261 Granville St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,0.2,0.3,15%,High Occupancy,11-100,NaN,-0.5,High,-123.127323,49.276628
204,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,4.1,4.6,0.2%,Reception Centre,101-1000,NaN,2.7,Low,-123.043079,49.227204
205,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,1.1,1.3,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
206,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,NaN,24-Sep-25,Adequate,24-Sep-25,...,4.0,3.9,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
207,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,1.3,2.3,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
222,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Partial (Exterior),24-Sep-25,...,1.2,#VALUE!,15%,Reception Centre,101-1000,NaN,-0.3,High,-123.039428,49.280804
223,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
224,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
225,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
231,294,CULT_1418_3102 Main St_Heritage Hall_MIXU,3102 Main St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,0.7,0.4,15%,Emergency Shelter,101-1000,NaN,0.2,High,-123.100839,49.257296

TODO: solve environment to install openseespy